FROM golang:1.25.3-trixie

# renovate: datasource=go depName=github.com/golangci/golangci-lint packageName=github.com/golangci/golangci-lint
ARG GOLANGCI_LINT_VERSION=v2.7.2

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

RUN go install golang.org/x/tools/gopls@v0.20.0
RUN go install github.com/go-delve/delve/cmd/dlv@v1.25.2
RUN go install github.com/josharian/impl@v1.4.0
RUN go install github.com/fatih/gomodifytags@v1.17.0
